### ISSUE TITLE
Does lazy ads affect impressions?

### ISSUE THREAD

**Issue by pentago** [wiley/madgex-lazy-ads#23]
I'm, as a marketing professional, interested to know **if** and **how** lazy ads affect impressions count?

**Comment by jameswragg** [comment]
Lazy Ads doesn't affect impressions as far as I know.

**Comment by pentago** [comment]
@jameswragg that's very unsure answer.

**Comment by jameswragg** [comment]
Lazy Ads was always developed as a stop-gap. That stop-gap is slightly less relevant today as some ad platforms now support RWD.
We have used LazyAds for years on hugely trafficked sites without issue, if you're concerned of impressions I suggest you put pressure on your ad platform provider to support a async loading and RWD.
